### ISSUE TITLE
Your repository name should use the standard frankenstyle Moodle naming convention

### ISSUE THREAD

**Issue by purnendudash** [edu-sharing/moodle-tiny_edusharing#1]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

also - put your files in the "root" of the repo - don't put them inside a folder called "moodle-mod_attendance" that way admins can use git submodules or subtrees to install your plugin in their sites.

not a blocker for approval - but really good to do.

**Comment by zieglermarian** [comment]
Hi Purnendu,

thank you very much for taking the time to help us improve our moodle plugin. Your input is very much appreciated! 

Concerning the issue: We renamed the github repository, so it should be fine now.

Regards,
Marian
