### ISSUE TITLE
Use of incorrect namespace

### ISSUE THREAD

**Issue by purnendudash** [edu-sharing/moodle-tiny_edusharing#2]
https://github.com/edu-sharing/-plugin-moodle-edu-sharing-tiny-editor/blob/6bf65a20646b5142b80b79c1220b372ca32aebc6/classes/privacy/provider.php#L25

Please refer to https://moodledev.io/general/development/policies/codingstyle#rules-for-level2

Your custom namespaces like fonts, help, model, pdf, report or privacy violate this naming rule. There are good reasons why it should be followed, mainly to avoid potential conflicts in the future. All these should be under classes/local/ namespace.

**Comment by zieglermarian** [comment]
Hi Purnendu,

thanks for the feedback. I checked the file and consulted the [documentation](https://moodledev.io/general/development/policies/codingstyle). Unfortunately, i was unable to find the problem, i probably missed something :( . Would you be so kind to tell me what i have to improve specifically?

Regards,
Marian

**Comment by zieglermarian** [comment]
@purnendudash Could you please have a look? Thanks!

**Comment by zieglermarian** [comment]
Solved
