### ISSUE TITLE
Files should use defined('MOODLE_INTERNAL') || die();

### ISSUE THREAD

**Issue by purnendudash** [edu-sharing/moodle-tiny_edusharing#3]
If a php file should not be loaded on it's own (class files etc) then you should be adding a check to:
defined('MOODLE_INTERNAL') || die();

at the top of the file.https://github.com/edu-sharing/-plugin-moodle-edu-sharing-tiny-editor/blob/6bf65a20646b5142b80b79c1220b372ca32aebc6/classes/privacy/provider.php#L26

**Comment by zieglermarian** [comment]
Hi Purnendu,

this has been addressed. The check has been added.

Regards,
Marian
