### ISSUE TITLE
Incorrect use of boilerplate

### ISSUE THREAD

**Issue by purnendudash** [edu-sharing/moodle-tiny_edusharing#4]
All plugin file should have some common explicit GPL license statement. Kindly check and include the same structure as defined on the doc below.

For more information on this see:
https://moodledev.io/general/community/plugincontribution/checklist#boilerplate

https://github.com/edu-sharing/-plugin-moodle-edu-sharing-tiny-editor/blob/6bf65a20646b5142b80b79c1220b372ca32aebc6/classes/plugininfo.php#L26

**Comment by zieglermarian** [comment]
Hi Purnendu,

thanks a lot for checking. We updated the boilerplate in all files and checked with [moodle code checker](https://moodle.org/plugins/local_codechecker). Everything is in order, now.

Regards,
Marian
