### ISSUE TITLE
Missing string $string['helplinktext'] required by tiny plugins

### ISSUE THREAD

**Issue by NJahreis** [edu-sharing/moodle-tiny_edusharing#5]
The function `getPluginMetadata` in
https://github.com/moodle/moodle/blob/b798633ae074eddd581724d0c5b1cdba01b9d909/lib/editor/tiny/amd/src/utils.js#L242-L250
expects the tiny plugins to define `$string['helplinktext']`. This leads to the following error then the function is invoked:

```
Got error 'PHP message: Debugging: Invalid get_string() identifier: 'helplinktext' or component 'tiny_edusharing'. Perhaps you are missing $string['helplinktext'] = ''; in /moodle/apache2/htdocs/lib/editor/tiny/plugins/edusharing/lang/en/tiny_edusharing.php? in
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 109 of /lib/external/externallib.php: call to core_string_manager_standard->get_string()
line ? of unknownfile: call to core_external::get_string()
line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
line 83 of /lib/ajax/service.php: call to core_external\\external_api::call_external_function()
line 33 of /lib/ajax/service-nologin.php: call to require_once()
', referer: MYMOODLE
```

Most tiny plugins just use the plugin name for this string so adding `$string['helplinktext'] = 'Edusharing';` to [lang/en/tiny_edusharing.php](https://github.com/edu-sharing/moodle-tiny_edusharing/blob/main/lang/en/tiny_edusharing.php) and [lang/en/tiny_edusharing.php](https://github.com/edu-sharing/moodle-tiny_edusharing/blob/main/lang/de/tiny_edusharing.php) will fix this issue.

**Comment by zieglermarian** [comment]
Hi Nikolai,

thank you very much for sour feedback! I added the entry to the language files.

Regards, Marian

**Comment by NJahreis** [comment]
Hi Marian,
You're welcome. 
Best regards, Nikolai
